### ISSUE TITLE
Not working on Safari macOS Ventura

### ISSUE THREAD

**Issue by dydx-git** [tillsanders/access-key-label-polyfill#2] opened 2023-01-24 08:50 UTC
Version 0.1.1

It does not work on safari. Tried pressing the access key with cmd, option, ctrl and fn. MacBook Air 2020 M1

**Comment by tillsanders** [comment] 2024-10-17 13:26
I released a new version today and tested again in Safari and I was unable to reproduce this issue. Also, Safari supports accessKeyLabel natively, so the polyfill should not even activate itself. To make sure it is not an issue related to your code, you can give the demo a try and see if that works: https://tillsanders.github.io/access-key-label-polyfill/

Closing for now.

**Closed as not planned** 2024-10-17 13:26 UTC
