### ISSUE TITLE
Wrong key combination on Edge

### ISSUE THREAD

**Issue by jonaskohl** [tillsanders/access-key-label-polyfill#1] opened 2021-08-03 15:07 UTC
I have an element with `F` as accesskey:

```html
<input type="text" accesskey="f" id="search-input" placeholder="Search&hellip;" autocomplete="off">
```

This library returns the `accessKeyLabel` as `Alt + f`. However, I need to press `Alt + SHIFT + f` to focus the element.

**Browser details:**
Microsoft Edge 92.0.902.62
Windows 10 2004 64 Bit

---

### EDIT

Also, it returns `undefined` for Chrome 92.0.4515.107

**Comment by tillsanders** [comment] 2024-10-17 13:29
I realise it's been over three years. However, I released a new version today, so here's an update!

It might be that something has changed in the meantime. I was unable to reproduce your issue with Edge on Windows with a current version. 

The issue with Chrome I could reproduce and it is now fixed. Thank you for reporting!

**Closed by tillsanders** 2024-10-17 13:29 UTC
